// this file was generated by better-cmake
// shl v0.8.1

#define shl_NAME "shl"
#define shl_AUTHOR "DaemonTsun"
#define shl_VERSION "0.8.1"
#define shl_VERSION_MAJOR 0
#define shl_VERSION_MINOR 8
#define shl_VERSION_PATCH 1
