// this file was generated by better-cmake
// shl v0.5.2

#define shl_AUTHOR "DaemonTsun"
#define shl_VERSION "0.5.2"
#define shl_VERSION_MAJOR 0
#define shl_VERSION_MINOR 5
#define shl_VERSION_PATCH 2
