// this file was generated by better-cmake
// shl v0.9.3

#define shl_NAME "shl"
#define shl_AUTHOR "DaemonTsun"
#define shl_VERSION "0.9.3"
#define shl_VERSION_MAJOR 0
#define shl_VERSION_MINOR 9
#define shl_VERSION_PATCH 3
